// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function ListEntries():Promise<Array<string>>;

export function ReadFromFile(arg1:string):Promise<string>;

export function WriteToFile(arg1:string,arg2:string):Promise<string>;
